#!/usr/bin/env ruby

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

use_shards = File.file? 'shard.yml'

# if `pgrep -f livepost` != ""
#   puts "killing off old server daemon"
#   run "pkill livepost"
# end

puts "installing shards"
if use_shards
  # update gem bundle
  run "shards update"
end

puts "building app"
run "crystal build /home/livepost/livepost/src/livepost.cr"