#!/usr/bin/env ruby
# hi this is mixflame love u
# i forgot libbson and i love you
# no this isnt a suicide note

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

use_shards = File.file? 'shard.yml'

puts "installing shards"
if use_shards
  # update gem bundle
  run "shards install"
end

puts "building app"
run "crystal build /home/mixflame/livepost/src/livepost.cr"

puts "killing off old server daemon"
run 'killall livepost'

puts "running livepost as a daemon"
run "nohup /home/mixflame/livepost/livepost &"